# Generated by Django 5.2.8 on 2025-11-20 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceTap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('IN', 'Clock In'), ('OUT', 'Clock Out')], max_length=3)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Attendance Tap',
                'verbose_name_plural': 'Attendance Taps',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('email_type', models.CharField(max_length=50)),
                ('recipient', models.EmailField(max_length=254)),
                ('employee_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], max_length=20)),
                ('details', models.TextField()),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('pin_code', models.CharField(max_length=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['employee_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('first_clock_in', models.TimeField(blank=True, null=True)),
                ('last_clock_out', models.TimeField(blank=True, null=True)),
                ('raw_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('break_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('final_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('current_status', models.CharField(choices=[('IN', 'Clocked In'), ('OUT', 'Clocked Out')], default='OUT', max_length=3)),
                ('tap_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Daily Summary',
                'verbose_name_plural': 'Daily Summaries',
                'ordering': ['-date', 'employee_name'],
                'unique_together': {('date', 'employee_id')},
            },
        ),
        migrations.CreateModel(
            name='TimesheetEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.CharField(max_length=200)),
                ('new_value', models.CharField(max_length=200)),
                ('reason', models.TextField()),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Timesheet Edit',
                'verbose_name_plural': 'Timesheet Edits',
                'ordering': ['-edited_at'],
            },
        ),
    ]
