# Generated by Django 5.2.8 on 2025-11-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='description',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='key',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='value',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='auto_clockout_interval',
            field=models.IntegerField(default=30, help_text='How often to check for auto clock-out (minutes)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='break_duration_hours',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Unpaid break duration (hours). Deducted from shifts > 5 hours', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_auto_clockout',
            field=models.BooleanField(default=True, help_text='Automatically clock out employees at office closing time or after shift hours'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_early_clockout_alerts',
            field=models.BooleanField(default=False, help_text='Send alerts when employees clock out before completing required shift hours'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_weekly_reports',
            field=models.BooleanField(default=True, help_text='Send weekly attendance reports to employees'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='office_end_time',
            field=models.TimeField(default='17:00', help_text='Office closing time (e.g., 17:00). No clock in/out after this time.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='office_start_time',
            field=models.TimeField(default='07:00', help_text='Office opening time (e.g., 07:00)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='required_shift_hours',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Required shift duration including break (hours)', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekly_report_day',
            field=models.IntegerField(default=4, help_text='Day of week to send reports (0=Monday, 4=Friday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekly_report_time',
            field=models.TimeField(default='17:00', help_text='Time to send weekly reports'),
        ),
    ]
