# Generated by Django 5.2.8 on 2025-11-25 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_systemsettings_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Attendance Report',
                'verbose_name_plural': 'Attendance Reports',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='employeeregistry',
            name='nfc_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeregistry',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
