# Generated by Django 5.2.8 on 2025-11-25 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancereport_employeeregistry_nfc_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='selected_employee',
            field=models.ForeignKey(blank=True, help_text='Select employee from dropdown', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='attendance.employeeregistry', verbose_name='Employee'),
        ),
    ]
