# Generated by Django 5.2.8 on 2025-12-22 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_dailysummary_selected_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='default_leave_hours_per_day',
            field=models.DecimalField(decimal_places=2, default=8.0, help_text='Default hours per day for leave calculations', max_digits=4),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='enable_leave_notifications',
            field=models.BooleanField(default=True, help_text='Send email notifications when leaves are created'),
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50)),
                ('employee_name', models.CharField(max_length=200)),
                ('leave_type', models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('UNPAID', 'Unpaid Leave')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('hours_per_day', models.DecimalField(decimal_places=2, default=8.0, max_digits=4)),
                ('total_days', models.IntegerField(default=0)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('selected_employee', models.ForeignKey(help_text='Select employee from dropdown', on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.employeeregistry')),
            ],
            options={
                'verbose_name': 'Leave Record',
                'verbose_name_plural': 'Leave Records',
                'ordering': ['-start_date'],
            },
        ),
    ]
