# Generated by Django 5.2.8 on 2026-01-13 03:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_systemsettings_default_leave_hours_per_day_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(choices=[('OFFS', 'Offshore'), ('IT', 'IT'), ('ADM', 'Admin'), ('WARE', 'Warehouse')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(help_text='Unique employee ID', max_length=50, unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('pin_hash', models.CharField(help_text='Hashed PIN for kiosk clock in/out', max_length=128)),
                ('pin_updated_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('MANAGER', 'Manager'), ('HR_ADMIN', 'HR/Admin')], default='EMPLOYEE', help_text='User role (Employee, Manager, HR/Admin)', max_length=20)),
                ('nfc_id', models.CharField(blank=True, help_text='NFC card ID (optional)', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(help_text='Employee department', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='attendance.department')),
                ('manager', models.ForeignKey(blank=True, help_text='Direct manager (for employees only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='attendance.employeeprofile')),
                ('user', models.OneToOneField(help_text='Django user account for login', on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee Profile (V2)',
                'verbose_name_plural': 'Employee Profiles (V2)',
                'ordering': ['employee_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='Department manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='attendance.employeeprofile'),
        ),
        migrations.CreateModel(
            name='PINHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_reason', models.CharField(choices=[('SELF_CHANGE', 'Employee Self-Change'), ('HR_RESET', 'HR Reset'), ('INITIAL_SETUP', 'Initial Setup')], help_text='Reason for PIN change', max_length=50)),
                ('old_pin_hash', models.CharField(blank=True, max_length=128)),
                ('new_pin_hash', models.CharField(max_length=128)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('changed_by', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pin_changes_made', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='pin_history', to='attendance.employeeprofile')),
            ],
            options={
                'verbose_name': 'PIN History',
                'verbose_name_plural': 'PIN History',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Morning Shift, Day Shift', max_length=100)),
                ('code', models.CharField(choices=[('MORN', 'Morning'), ('DAY', 'Day'), ('EVE', 'Evening'), ('NIGHT', 'Night')], max_length=20, unique=True)),
                ('start_time', models.TimeField(help_text='Shift start time (e.g., 07:00)')),
                ('end_time', models.TimeField(help_text='Shift end time (e.g., 15:00)')),
                ('scheduled_hours', models.DecimalField(decimal_places=2, default=8.0, help_text='Scheduled shift duration (hours)', max_digits=4)),
                ('break_duration_hours', models.DecimalField(decimal_places=2, default=0.5, help_text='Break duration (hours)', max_digits=4)),
                ('early_arrival_grace_minutes', models.IntegerField(default=15, help_text='Minutes early is considered normal (beyond this = Early Bird)')),
                ('late_departure_grace_minutes', models.IntegerField(default=15, help_text='Minutes late is considered normal')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, help_text='Department this shift belongs to (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='attendance.department')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='default_shift',
            field=models.ForeignKey(blank=True, help_text='Default shift for this employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='attendance.shift'),
        ),
        migrations.CreateModel(
            name='TILBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_earned', models.DecimalField(decimal_places=2, default=0, help_text='Total hours earned', max_digits=6)),
                ('total_used', models.DecimalField(decimal_places=2, default=0, help_text='Total hours used', max_digits=6)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Current balance (earned - used)', max_digits=6)),
                ('last_calculated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='til_balance', to='attendance.employeeprofile')),
            ],
            options={
                'verbose_name': 'TIL Balance',
                'verbose_name_plural': 'TIL Balances',
                'ordering': ['employee__employee_name'],
            },
        ),
        migrations.CreateModel(
            name='TILRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('til_type', models.CharField(choices=[('EARNED_EARLY', 'Earned - Manager-Approved Early Start'), ('EARNED_OT', 'Earned - Manager-Approved Overtime'), ('USED', 'Used - TIL Leave'), ('ADJUSTED', 'Manual Adjustment')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('hours', models.DecimalField(decimal_places=2, help_text='Positive for earned, negative for used', max_digits=5)),
                ('date', models.DateField(help_text='Date TIL was earned/used')),
                ('reason', models.TextField(help_text='Reason for TIL')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='til_approvals', to='attendance.employeeprofile')),
                ('daily_summary', models.ForeignKey(blank=True, help_text='Related daily summary', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='til_records', to='attendance.dailysummary')),
                ('employee', models.ForeignKey(help_text='Employee', on_delete=django.db.models.deletion.CASCADE, related_name='til_records', to='attendance.employeeprofile')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Who requested this TIL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='til_requests', to='attendance.employeeprofile')),
            ],
            options={
                'verbose_name': 'TIL Record',
                'verbose_name_plural': 'TIL Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for this shift assignment')),
                ('custom_start_time', models.TimeField(blank=True, help_text='Custom start time (overrides shift template)', null=True)),
                ('custom_end_time', models.TimeField(blank=True, help_text='Custom end time (overrides shift template)', null=True)),
                ('pre_approved_early_start', models.BooleanField(default=False, help_text='Manager pre-approved early start')),
                ('pre_approved_overtime', models.BooleanField(default=False, help_text='Manager pre-approved overtime')),
                ('approved_early_minutes', models.IntegerField(default=0, help_text='Pre-approved early start minutes')),
                ('approved_overtime_hours', models.DecimalField(decimal_places=2, default=0, help_text='Pre-approved overtime hours', max_digits=4)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_shift_assignments', to='attendance.employeeprofile')),
                ('employee', models.ForeignKey(help_text='Employee assigned to this shift', on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='attendance.employeeprofile')),
                ('shift', models.ForeignKey(help_text='Shift template', on_delete=django.db.models.deletion.CASCADE, to='attendance.shift')),
            ],
            options={
                'verbose_name': 'Shift Assignment',
                'verbose_name_plural': 'Shift Assignments',
                'ordering': ['-date', 'employee__employee_name'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
