# Generated by Django 5.2.8 on 2026-01-18 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_department_employeeprofile_department_manager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Manager who approved/rejected', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to='attendance.employeeprofile'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='employee_profile',
            field=models.ForeignKey(blank=True, help_text='Employee profile (V2)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.employeeprofile'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='manager_comments',
            field=models.TextField(blank=True, help_text='Manager comments'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejection'),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='leaverecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='leave_type',
            field=models.CharField(choices=[('ANNUAL', 'Annual Leave'), ('SICK', 'Sick Leave'), ('UNPAID', 'Unpaid Leave'), ('TIL', 'Time in Lieu')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverecord',
            name='selected_employee',
            field=models.ForeignKey(blank=True, help_text='Select employee from dropdown (V1)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_records', to='attendance.employeeregistry'),
        ),
    ]
