# Generated by Django 5.2.8 on 2026-05-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_sync_ip_fields_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregistry',
            name='allowed_ip_addresses',
            field=models.TextField(blank=True, help_text='Comma-separated list of allowed IP addresses (e.g., 192.168.1.100, 10.0.0.1)'),
        ),
        migrations.AddField(
            model_name='employeeregistry',
            name='ip_restriction_enabled',
            field=models.BooleanField(default=False, help_text='Enable IP restriction for this employee'),
        ),
        migrations.AddField(
            model_name='employeeregistry',
            name='ip_restriction_message',
            field=models.CharField(blank=True, default='Access restricted to authorized IP addresses only', help_text='Custom message to show when IP is not allowed', max_length=255),
        ),
    ]
